from app.languages import LANGUAGES


def _same(text: str) -> dict[str, str]:
    return {code: text for code in LANGUAGES}


TEXTS = {
    "select_language": {
        "en": "Please choose your language:",
        "es": "Selecciona tu idioma:",
        "fr": "Veuillez choisir votre langue :",
        "de": "Bitte wählen Sie Ihre Sprache:",
        "pt": "Escolha seu idioma:",
        "ar": "يرجى اختيار لغتك:",
        "hi": "कृपया अपनी भाषा चुनें:",
        "id": "Silakan pilih bahasa Anda:",
        "tr": "Lütfen dilinizi seçin:",
        "ru": "Пожалуйста, выберите язык:",
        "nl": "Kies uw taal:",  # ✅ ADD
    },
    "welcome": {
        "en": "Welcome to The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ You now have access to our Exclusive Forex & Gold trade ideas, a structured onboarding path, and our private alert room.\n\nLet’s start with your onboarding.",
        "es": "Bienvenido a The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Ahora tienes acceso a nuestras ideas exclusivas de trading en Forex y Oro, un proceso de incorporación estructurado y nuestra sala privada de alertas.\n\nComencemos con tu onboarding.",
        "fr": "Bienvenue sur The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Vous avez maintenant accès à nos idées exclusives de trading Forex et Or, un parcours d’intégration structuré et notre salle privée d’alertes.\n\nCommençons votre onboarding.",
        "de": "Willkommen bei The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Du hast jetzt Zugang zu unseren exklusiven Forex- und Gold-Trading-Ideen, einem strukturierten Onboarding-Prozess und unserem privaten Signalraum.\n\nLass uns mit deinem Onboarding beginnen.",
        "pt": "Bem-vindo ao The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Agora você tem acesso às nossas ideias exclusivas de trading em Forex e Ouro, um processo de onboarding estruturado e nossa sala privada de alertas.\n\nVamos começar com seu onboarding.",
        "ar": "مرحبًا بك في The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ لديك الآن وصول إلى أفكار تداول الفوركس والذهب الحصرية لدينا، ومسار إعداد منظم، وغرفة التنبيهات الخاصة بنا.\n\nلنبدأ عملية الإعداد.",
        "hi": "The FX Hustle Room Exclusive Trading Alerts में आपका स्वागत है।\n\n➡️ अब आपके पास हमारे एक्सक्लूसिव फॉरेक्स और गोल्ड ट्रेड आइडियाज़, एक संरचित ऑनबोर्डिंग प्रक्रिया और हमारे प्राइवेट अलर्ट रूम तक पहुंच है।\n\nआइए आपका ऑनबोर्डिंग शुरू करें।",
        "id": "Selamat datang di The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Sekarang Anda memiliki akses ke ide trading Forex & Emas eksklusif kami, alur onboarding terstruktur, dan ruang alert privat kami.\n\nMari mulai onboarding Anda.",
        "tr": "The FX Hustle Room Exclusive Trading Alerts'e hoş geldiniz.\n\n➡️ Artık özel Forex ve Altın işlem fikirlerimize, yapılandırılmış bir onboarding sürecine ve özel sinyal odamıza erişiminiz var.\n\nOnboarding sürecinize başlayalım.",
        "ru": "Добро пожаловать в The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Теперь у вас есть доступ к нашим эксклюзивным торговым идеям по Forex и золоту, структурированному онбордингу и нашей приватной комнате сигналов.\n\nДавайте начнем ваше онбординг.",
        "nl": "Welkom bij The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Je hebt nu toegang tot onze exclusieve Forex- en goud handelsideeën, een gestructureerd onboardingproces en onze privé alertgroep.\n\nLaten we beginnen met je onboarding.",  # ✅ ADD
    },
    "terms": {
        "en": "Please read and accept our Rules & Terms to continue.\n⚠️ Trading involves risk. You are responsible for your own decisions.",
        "es": "Lee y acepta nuestras Reglas y Términos para continuar.\n⚠️ El trading implica riesgo. Eres responsable de tus propias decisiones.",
        "fr": "Veuillez lire et accepter nos Règles et Conditions pour continuer.\n⚠️ Le trading comporte des risques. Vous êtes responsable de vos propres décisions.",
        "de": "Bitte lies und akzeptiere unsere Regeln und Bedingungen, um fortzufahren.\n⚠️ Trading ist mit Risiken verbunden. Du bist für deine eigenen Entscheidungen verantwortlich.",
        "pt": "Leia e aceite nossos Termos e Regras para continuar.\n⚠️ O trading envolve risco. Você é responsável por suas próprias decisões.",
        "ar": "يرجى قراءة القواعد والشروط والموافقة عليها للمتابعة.\n⚠️ التداول ينطوي على مخاطر. أنت مسؤول عن قراراتك الخاصة.",
        "hi": "जारी रखने के लिए कृपया हमारे नियम और शर्तें पढ़ें और स्वीकार करें।\n⚠️ ट्रेडिंग में जोखिम शामिल है। अपने निर्णयों के लिए आप स्वयं जिम्मेदार हैं।",
        "id": "Silakan baca dan setujui Aturan & Ketentuan kami untuk melanjutkan.\n⚠️ Trading memiliki risiko. Anda bertanggung jawab atas keputusan Anda sendiri.",
        "tr": "Devam etmek için lütfen Kurallarımızı ve Şartlarımızı okuyup kabul edin.\n⚠️ İşlem yapmak risk içerir. Kendi kararlarınızdan siz sorumlusunuz.",
        "ru": "Пожалуйста, прочитайте и примите наши Правила и Условия, чтобы продолжить.\n⚠️ Торговля связана с риском. Вы несете ответственность за свои решения.",
        "nl": "Lees en accepteer onze Regels en Voorwaarden om door te gaan.\n⚠️ Trading bevat risico's. U bent verantwoordelijk voor uw eigen beslissingen.",  # ✅ ADD
    },
    "create_account": {
        "en": "Step 1️⃣ — Create a live trading account:\n\nRegister with this link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nRecommended platform: MetaTrader 5 (mobile app is fine)\nAccount Type: RAW-ECN\nAccount Currency: EUR",
        "es": "Paso 1️⃣ — Crea una cuenta de trading real:\n\nRegístrate con este enlace:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlataforma recomendada: MetaTrader 5\nTipo de cuenta: RAW-ECN\nMoneda: EUR",
        "fr": "Étape 1️⃣ — Créez un compte de trading réel :\n\nInscrivez-vous via ce lien :\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlateforme recommandée : MetaTrader 5\nType de compte : RAW-ECN\nDevise : EUR",
        "de": "Schritt 1️⃣ — Erstelle ein Live-Trading-Konto:\n\nRegistriere dich über diesen Link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nEmpfohlene Plattform: MetaTrader 5\nKontotyp: RAW-ECN\nWährung: EUR",
        "pt": "Passo 1️⃣ — Crie uma conta de trading real:\n\nRegistre-se neste link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlataforma recomendada: MetaTrader 5\nTipo de conta: RAW-ECN\nMoeda: EUR",
        "ar": "الخطوة 1️⃣ — أنشئ حساب تداول حقيقي:\n\nسجل من خلال هذا الرابط:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nالمنصة الموصى بها: MetaTrader 5\nنوع الحساب: RAW-ECN\nالعملة: EUR",
        "hi": "स्टेप 1️⃣ — लाइव ट्रेडिंग अकाउंट बनाएं:\n\nइस लिंक से रजिस्टर करें:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nसुझाई गई प्लेटफॉर्म: MetaTrader 5\nअकाउंट प्रकार: RAW-ECN\nकरेंसी: EUR",
        "id": "Langkah 1️⃣ — Buat akun trading live:\n\nDaftar melalui link ini:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlatform yang direkomendasikan: MetaTrader 5\nTipe akun: RAW-ECN\nMata uang: EUR",
        "tr": "Adım 1️⃣ — Canlı işlem hesabı oluştur:\n\nBu linkten kayıt ol:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nÖnerilen platform: MetaTrader 5\nHesap türü: RAW-ECN\nPara birimi: EUR",
        "ru": "Шаг 1️⃣ — Создайте реальный торговый счет:\n\nЗарегистрируйтесь по ссылке:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nРекомендуемая платформа: MetaTrader 5\nТип счета: RAW-ECN\nВалюта: EUR",
        "nl": "Stap 1️⃣ — Maak een live trading account aan:\n\nRegistreer via deze link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nAanbevolen platform: MetaTrader 5\nAccounttype: RAW-ECN\nValuta: EUR",
    },
    "verify_identity": {
        "en": "Step 2️⃣ — Verify your identity:\n\nComplete the identity verification inside VT Markets (one-time only) to fully activate your account.",
        "es": "Paso 2️⃣ — Verifica tu identidad:\n\nCompleta la verificación en VT Markets para activar tu cuenta.",
        "fr": "Étape 2️⃣ — Vérifiez votre identité :\n\nComplétez la vérification dans VT Markets.",
        "de": "Schritt 2️⃣ — Verifiziere deine Identität:\n\nSchließe die Verifizierung bei VT Markets ab.",
        "pt": "Passo 2️⃣ — Verifique sua identidade:\n\nComplete a verificação na VT Markets.",
        "ar": "الخطوة 2️⃣ — تحقق من هويتك:\n\nأكمل التحقق داخل VT Markets.",
        "hi": "स्टेप 2️⃣ — अपनी पहचान सत्यापित करें:\n\nVT Markets में सत्यापन पूरा करें।",
        "id": "Langkah 2️⃣ — Verifikasi identitas Anda:\n\nSelesaikan verifikasi di VT Markets.",
        "tr": "Adım 2️⃣ — Kimliğini doğrula:\n\nVT Markets içinde doğrulamayı tamamla.",
        "ru": "Шаг 2️⃣ — Подтвердите личность:\n\nЗавершите проверку в VT Markets.",
        "nl": "Stap 2️⃣ — Verifieer je identiteit:\n\nVoltooi verificatie binnen VT Markets.",
    },
    "fund_account": {
        "en": "Step 3️⃣ — Fund your account:\n\nTo trade XAUUSD using our execution model and required lot sizes, a minimum deposit of €350 is required.\n\n✅ After your deposit is confirmed, your balance will be doubled, providing you with additional capital to trade.",
        "es": "Paso 3️⃣ — Deposita en tu cuenta:\n\nPara operar XAUUSD, se requiere un depósito mínimo de €350.\n\n✅ Después de confirmar tu depósito, tu saldo se duplicará, dándote más capital para operar.",
        "fr": "Étape 3️⃣ — Approvisionnez votre compte :\n\nPour trader XAUUSD, un dépôt minimum de 350€ est requis.\n\n✅ Après confirmation du dépôt, votre solde sera doublé.",
        "de": "Schritt 3️⃣ — Konto aufladen:\n\nFür XAUUSD ist eine Mindesteinzahlung von 350€ erforderlich.\n\n✅ Nach Bestätigung wird dein Guthaben verdoppelt.",
        "pt": "Passo 3️⃣ — Financie sua conta:\n\nDepósito mínimo de €350 para negociar XAUUSD.\n\n✅ Após confirmação, seu saldo será dobrado.",
        "ar": "الخطوة 3️⃣ — قم بتمويل حسابك:\n\nالحد الأدنى للإيداع هو 350€ للتداول.\n\n✅ بعد التأكيد، سيتم مضاعفة رصيدك.",
        "hi": "स्टेप 3️⃣ — अपने अकाउंट में फंड करें:\n\nXAUUSD ट्रेड के लिए €350 न्यूनतम जमा आवश्यक है।\n\n✅ जमा के बाद बैलेंस डबल होगा।",
        "id": "Langkah 3️⃣ — Deposit dana:\n\nMinimal €350 untuk trading XAUUSD.\n\n✅ Setelah konfirmasi, saldo akan digandakan.",
        "tr": "Adım 3️⃣ — Hesabını fonla:\n\nXAUUSD için minimum €350 gerekir.\n\n✅ Onay sonrası bakiye iki katına çıkar.",
        "ru": "Шаг 3️⃣ — Пополните счет:\n\nМинимум €350 для торговли XAUUSD.\n\n✅ После подтверждения баланс удваивается.",
        "nl": "Stap 3️⃣ — Stort geld:\n\nMinimaal €350 vereist voor XAUUSD.\n\n✅ Na bevestiging wordt saldo verdubbeld.",
    },
    "upload_deposit_prompt": {
        "en": "Upload deposit proof.",
        "es": "Sube comprobante.",
        "fr": "Téléchargez preuve.",
        "de": "Nachweis hochladen.",
        "pt": "Envie comprovante.",
        "ar": "ارفع الإثبات.",
        "hi": "प्रूफ अपलोड करें।",
        "id": "Upload bukti.",
        "tr": "Kanıt yükle.",
        "ru": "Загрузите доказательство.",
        "nl": "Upload bewijs.",
    },
    "deposit_pending": {
        "en": "Deposit pending approval.",
        "es": "Pendiente.",
        "fr": "En attente.",
        "de": "Ausstehend.",
        "pt": "Pendente.",
        "ar": "قيد الانتظار.",
        "hi": "पेंडिंग।",
        "id": "Menunggu.",
        "tr": "Bekliyor.",
        "ru": "Ожидается.",
        "nl": "In afwachting.",
    },
    "deposit_approved": {
        "en": "Your deposit has been approved.\n\nRisk management is a critical aspect of trading. Before entering any trades, make sure you have reviewed the risk management module in your online training environment.\n\nDo you understand the importance of risk management?",
        "es": "Tu depósito ha sido aprobado.\n\nLa gestión de riesgos es clave en el trading. ¿La entiendes?",
        "fr": "Votre dépôt a été approuvé.\n\nLa gestion des risques est essentielle en trading.",
        "de": "Deine Einzahlung wurde bestätigt.\n\nRisikomanagement ist entscheidend.",
        "pt": "Seu depósito foi aprovado.\n\nGestão de risco é essencial.",
        "ar": "تمت الموافقة على الإيداع.\n\nإدارة المخاطر مهمة جدًا.",
        "hi": "आपका डिपॉज़िट स्वीकृत हो गया है।\n\nरिस्क मैनेजमेंट बहुत महत्वपूर्ण है।",
        "id": "Deposit Anda disetujui.\n\nManajemen risiko sangat penting.",
        "tr": "Yatırımınız onaylandı.\n\nRisk yönetimi çok önemlidir.",
        "ru": "Депозит подтвержден.\n\nУправление рисками очень важно.",
        "nl": "Je storting is goedgekeurd.\n\nRisicobeheer is zeer belangrijk.",
    },
    "deposit_rejected": {
        "en": "Your deposit proof was rejected. Please upload it again.",
        "es": "Tu comprobante fue rechazado. Súbelo de nuevo.",
        "fr": "Votre preuve a été rejetée. Veuillez la télécharger à nouveau.",
        "de": "Nachweis abgelehnt. Bitte erneut hochladen.",
        "pt": "Comprovante rejeitado. Envie novamente.",
        "ar": "تم رفض الإثبات. أعد الرفع.",
        "hi": "आपका प्रूफ अस्वीकार किया गया। फिर से अपलोड करें।",
        "id": "Bukti ditolak. Upload ulang.",
        "tr": "Kanıt reddedildi. Tekrar yükle.",
        "ru": "Доказательство отклонено. Загрузите снова.",
        "nl": "Bewijs afgewezen. Upload opnieuw.",
    },

"risk": {
    "en": "Risk management is a critical aspect of trading.\n\nBefore entering any trades, make sure you have reviewed the risk management module in your online training environment.\n\nDo you understand the importance of risk management?",
    "es": "La gestión de riesgo es clave.\n\n¿La entiendes?",
    "fr": "La gestion du risque est essentielle.\n\nComprenez-vous cela ?",
    "de": "Risikomanagement ist entscheidend.\n\nVerstehst du das?",
    "pt": "Gestão de risco é essencial.\n\nVocê entende?",
    "ar": "إدارة المخاطر مهمة.\n\nهل تفهم ذلك؟",
    "hi": "रिस्क मैनेजमेंट जरूरी है।\n\nक्या आप समझते हैं?",
    "id": "Manajemen risiko penting.\n\nApakah Anda paham?",
    "tr": "Risk yönetimi önemlidir.\n\nAnlıyor musun?",
    "ru": "Управление рисками важно.\n\nВы понимаете?",
    "nl": "Risicobeheer is belangrijk.\n\nBegrijp je dit?",
},

"risk_no": {
    "en": "Risk management is the foundation of successful trading. Make sure you understand this before placing your first trade.",
    "es": "La gestión de riesgo es clave antes de operar.",
    "fr": "Comprenez le risque avant de trader.",
    "de": "Verstehe Risiko vor dem Trading.",
    "pt": "Entenda risco antes de operar.",
    "ar": "افهم المخاطر أولاً.",
    "hi": "पहले जोखिम समझें।",
    "id": "Pahami risiko dulu.",
    "tr": "Önce riski anla.",
    "ru": "Сначала поймите риск.",
    "nl": "Begrijp eerst risico.",
},

"ready_to_trade": {
    "en": "You are ready to place your first trades with us.\n\nIf you’re not sure how to connect your VT Markets account to MetaTrader 4 or 5 and start trading, watch the video below.",
    "es": "Ya estás listo para realizar tus primeras operaciones con nosotros.\n\nSi no sabes cómo conectar tu cuenta de VT Markets a MetaTrader 4 o 5 y comenzar a operar, mira el video a continuación.",
    "fr": "Vous êtes prêt à effectuer vos premières opérations avec nous.\n\nSi vous ne savez pas comment connecter votre compte VT Markets à MetaTrader 4 ou 5, regardez la vidéo ci-dessous.",
    "de": "Du bist bereit, deine ersten Trades mit uns zu platzieren.\n\nWenn du nicht weißt, wie du dein VT Markets Konto mit MetaTrader 4 oder 5 verbindest, sieh dir das Video unten an.",
    "pt": "Você está pronto para fazer seus primeiros trades conosco.\n\nSe não souber como conectar sua conta VT Markets ao MetaTrader 4 ou 5, assista ao vídeo abaixo.",
    "ar": "أنت الآن جاهز لبدء التداول معنا.\n\nإذا لم تكن تعرف كيفية ربط حساب VT Markets الخاص بك بـ MetaTrader 4 أو 5، شاهد الفيديو أدناه.",
    "hi": "आप अब हमारे साथ अपना पहला ट्रेड करने के लिए तैयार हैं।\n\nयदि आपको नहीं पता कि VT Markets अकाउंट को MetaTrader 4 या 5 से कैसे जोड़ें, तो नीचे दिया गया वीडियो देखें।",
    "id": "Anda siap untuk mulai trading bersama kami.\n\nJika Anda belum tahu cara menghubungkan akun VT Markets ke MetaTrader 4 atau 5, tonton video di bawah ini.",
    "tr": "Artık bizimle ilk işlemlerinizi yapmaya hazırsınız.\n\nVT Markets hesabınızı MetaTrader 4 veya 5’e nasıl bağlayacağınızı bilmiyorsanız aşağıdaki videoyu izleyin.",
    "ru": "Вы готовы начать свои первые сделки с нами.\n\nЕсли вы не знаете, как подключить счет VT Markets к MetaTrader 4 или 5, посмотрите видео ниже.",
    "nl": "Je bent klaar om je eerste trades met ons te plaatsen.\n\nAls je niet weet hoe je je VT Markets account koppelt aan MetaTrader 4 of 5, bekijk dan de video hieronder."
},
    "premium_granted": {
        "en": "Access granted.\n\nClick below to join.",
        "es": "Acceso concedido.",
        "fr": "Accès accordé.",
        "de": "Zugang gewährt.",
        "pt": "Acesso concedido.",
        "ar": "تم منح الوصول.",
        "hi": "एक्सेस मिल गया।",
        "id": "Akses diberikan.",
        "tr": "Erişim verildi.",
        "ru": "Доступ открыт.",
        "nl": "Toegang verleend.",
    },
    "unsupported_file": {
        "en": "Unsupported file. Please upload an image or PDF.",
        "es": "Archivo no compatible. Sube una imagen o PDF.",
        "fr": "Fichier non pris en charge. Téléchargez une image ou PDF.",
        "de": "Datei nicht unterstützt. Bitte Bild oder PDF hochladen.",
        "pt": "Arquivo não suportado. Envie imagem ou PDF.",
        "ar": "ملف غير مدعوم. ارفع صورة أو PDF.",
        "hi": "अमान्य फ़ाइल। इमेज या PDF अपलोड करें।",
        "id": "File tidak didukung. Upload gambar atau PDF.",
        "tr": "Desteklenmeyen dosya. Görsel veya PDF yükle.",
        "ru": "Файл не поддерживается. Загрузите изображение или PDF.",
        "nl": "Bestand niet ondersteund. Upload een afbeelding of PDF.",
    },

    "status_waiting_deposit": {
        "en": "Your deposit is still pending approval.",
        "es": "Tu depósito está pendiente.",
        "fr": "Votre dépôt est en attente.",
        "de": "Deine Einzahlung wartet.",
        "pt": "Seu depósito está pendente.",
        "ar": "الإيداع قيد الانتظار.",
        "hi": "आपका डिपॉज़िट लंबित है।",
        "id": "Deposit masih menunggu.",
        "tr": "Yatırım beklemede.",
        "ru": "Депозит ожидает.",
        "nl": "Je storting is in afwachting.",
    },
    "admin_deposit_caption": _same("New deposit proof submitted."),
    "admin_trade_caption": _same("New first trade proof submitted."),
    "trading_video_missing": _same("Trading video is not configured yet. The admin needs to upload it first."),
    "admin_only": _same("This action is only available to admins."),
    "saved": {
        "en": "Saved successfully.",
        "es": "Guardado.",
        "fr": "Enregistré.",
        "de": "Gespeichert.",
        "pt": "Salvo.",
        "ar": "تم الحفظ.",
        "hi": "सेव हो गया।",
        "id": "Disimpan.",
        "tr": "Kaydedildi.",
        "ru": "Сохранено.",
        "nl": "Opgeslagen.",
    },
}


def t(key: str, language: str) -> str:
    bundle = TEXTS.get(key, {})
    return bundle.get(language) or bundle.get("en") or key
