from app.languages import LANGUAGES


def _same(text: str) -> dict[str, str]:
    return {code: text for code in LANGUAGES}


TEXTS = {
    "select_language": {
        "en": "Please choose your language:",
        "es": "Selecciona tu idioma:",
        "fr": "Veuillez choisir votre langue :",
        "de": "Bitte wählen Sie Ihre Sprache:",
        "pt": "Escolha seu idioma:",
        "ar": "يرجى اختيار لغتك:",
        "hi": "कृपया अपनी भाषा चुनें:",
        "id": "Silakan pilih bahasa Anda:",
        "tr": "Lütfen dilinizi seçin:",
        "ru": "Пожалуйста, выберите язык:",
        "nl": "Kies uw taal:",  # ✅ ADD
    },
    "welcome": {
        "en": "Welcome to The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ You now have access to our Exclusive Forex & Gold trade ideas, a structured onboarding path, and our private alert room.\n\nLet’s start with your onboarding.",
        "es": "Bienvenido a The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Ahora tienes acceso a nuestras ideas exclusivas de trading en Forex y Oro, un proceso de incorporación estructurado y nuestra sala privada de alertas.\n\nComencemos con tu onboarding.",
        "fr": "Bienvenue sur The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Vous avez maintenant accès à nos idées exclusives de trading Forex et Or, un parcours d’intégration structuré et notre salle privée d’alertes.\n\nCommençons votre onboarding.",
        "de": "Willkommen bei The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Du hast jetzt Zugang zu unseren exklusiven Forex- und Gold-Trading-Ideen, einem strukturierten Onboarding-Prozess und unserem privaten Signalraum.\n\nLass uns mit deinem Onboarding beginnen.",
        "pt": "Bem-vindo ao The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Agora você tem acesso às nossas ideias exclusivas de trading em Forex e Ouro, um processo de onboarding estruturado e nossa sala privada de alertas.\n\nVamos começar com seu onboarding.",
        "ar": "مرحبًا بك في The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ لديك الآن وصول إلى أفكار تداول الفوركس والذهب الحصرية لدينا، ومسار إعداد منظم، وغرفة التنبيهات الخاصة بنا.\n\nلنبدأ عملية الإعداد.",
        "hi": "The FX Hustle Room Exclusive Trading Alerts में आपका स्वागत है।\n\n➡️ अब आपके पास हमारे एक्सक्लूसिव फॉरेक्स और गोल्ड ट्रेड आइडियाज़, एक संरचित ऑनबोर्डिंग प्रक्रिया और हमारे प्राइवेट अलर्ट रूम तक पहुंच है।\n\nआइए आपका ऑनबोर्डिंग शुरू करें।",
        "id": "Selamat datang di The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Sekarang Anda memiliki akses ke ide trading Forex & Emas eksklusif kami, alur onboarding terstruktur, dan ruang alert privat kami.\n\nMari mulai onboarding Anda.",
        "tr": "The FX Hustle Room Exclusive Trading Alerts'e hoş geldiniz.\n\n➡️ Artık özel Forex ve Altın işlem fikirlerimize, yapılandırılmış bir onboarding sürecine ve özel sinyal odamıza erişiminiz var.\n\nOnboarding sürecinize başlayalım.",
        "ru": "Добро пожаловать в The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Теперь у вас есть доступ к нашим эксклюзивным торговым идеям по Forex и золоту, структурированному онбордингу и нашей приватной комнате сигналов.\n\nДавайте начнем ваше онбординг.",
        "nl": "Welkom bij The FX Hustle Room Exclusive Trading Alerts.\n\n➡️ Je hebt nu toegang tot onze exclusieve Forex- en goud handelsideeën, een gestructureerd onboardingproces en onze privé alertgroep.\n\nLaten we beginnen met je onboarding.",  # ✅ ADD
    },
    "terms": {
        "en": "Please read and accept our Rules & Terms to continue.\n⚠️ Trading involves risk. You are responsible for your own decisions.",
        "es": "Lee y acepta nuestras Reglas y Términos para continuar.\n⚠️ El trading implica riesgo. Eres responsable de tus propias decisiones.",
        "fr": "Veuillez lire et accepter nos Règles et Conditions pour continuer.\n⚠️ Le trading comporte des risques. Vous êtes responsable de vos propres décisions.",
        "de": "Bitte lies und akzeptiere unsere Regeln und Bedingungen, um fortzufahren.\n⚠️ Trading ist mit Risiken verbunden. Du bist für deine eigenen Entscheidungen verantwortlich.",
        "pt": "Leia e aceite nossos Termos e Regras para continuar.\n⚠️ O trading envolve risco. Você é responsável por suas próprias decisões.",
        "ar": "يرجى قراءة القواعد والشروط والموافقة عليها للمتابعة.\n⚠️ التداول ينطوي على مخاطر. أنت مسؤول عن قراراتك الخاصة.",
        "hi": "जारी रखने के लिए कृपया हमारे नियम और शर्तें पढ़ें और स्वीकार करें।\n⚠️ ट्रेडिंग में जोखिम शामिल है। अपने निर्णयों के लिए आप स्वयं जिम्मेदार हैं।",
        "id": "Silakan baca dan setujui Aturan & Ketentuan kami untuk melanjutkan.\n⚠️ Trading memiliki risiko. Anda bertanggung jawab atas keputusan Anda sendiri.",
        "tr": "Devam etmek için lütfen Kurallarımızı ve Şartlarımızı okuyup kabul edin.\n⚠️ İşlem yapmak risk içerir. Kendi kararlarınızdan siz sorumlusunuz.",
        "ru": "Пожалуйста, прочитайте и примите наши Правила и Условия, чтобы продолжить.\n⚠️ Торговля связана с риском. Вы несете ответственность за свои решения.",
        "nl": "Lees en accepteer onze Regels en Voorwaarden om door te gaan.\n⚠️ Trading bevat risico's. U bent verantwoordelijk voor uw eigen beslissingen.",  # ✅ ADD
    },
    "create_account": {
        "en": "Step 1️⃣ — Create a live trading account:\n\nRegister with this link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nRecommended platform: MetaTrader 5 (mobile app is fine)\nAccount Type: RAW-ECN\nAccount Currency: EUR",
        "es": "Paso 1️⃣ — Crea una cuenta de trading real:\n\nRegístrate con este enlace:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlataforma recomendada: MetaTrader 5\nTipo de cuenta: RAW-ECN\nMoneda: EUR",
        "fr": "Étape 1️⃣ — Créez un compte de trading réel :\n\nInscrivez-vous via ce lien :\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlateforme recommandée : MetaTrader 5\nType de compte : RAW-ECN\nDevise : EUR",
        "de": "Schritt 1️⃣ — Erstelle ein Live-Trading-Konto:\n\nRegistriere dich über diesen Link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nEmpfohlene Plattform: MetaTrader 5\nKontotyp: RAW-ECN\nWährung: EUR",
        "pt": "Passo 1️⃣ — Crie uma conta de trading real:\n\nRegistre-se neste link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlataforma recomendada: MetaTrader 5\nTipo de conta: RAW-ECN\nMoeda: EUR",
        "ar": "الخطوة 1️⃣ — أنشئ حساب تداول حقيقي:\n\nسجل من خلال هذا الرابط:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nالمنصة الموصى بها: MetaTrader 5\nنوع الحساب: RAW-ECN\nالعملة: EUR",
        "hi": "स्टेप 1️⃣ — लाइव ट्रेडिंग अकाउंट बनाएं:\n\nइस लिंक से रजिस्टर करें:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nसुझाई गई प्लेटफॉर्म: MetaTrader 5\nअकाउंट प्रकार: RAW-ECN\nकरेंसी: EUR",
        "id": "Langkah 1️⃣ — Buat akun trading live:\n\nDaftar melalui link ini:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nPlatform yang direkomendasikan: MetaTrader 5\nTipe akun: RAW-ECN\nMata uang: EUR",
        "tr": "Adım 1️⃣ — Canlı işlem hesabı oluştur:\n\nBu linkten kayıt ol:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nÖnerilen platform: MetaTrader 5\nHesap türü: RAW-ECN\nPara birimi: EUR",
        "ru": "Шаг 1️⃣ — Создайте реальный торговый счет:\n\nЗарегистрируйтесь по ссылке:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nРекомендуемая платформа: MetaTrader 5\nТип счета: RAW-ECN\nВалюта: EUR",
        "nl": "Stap 1️⃣ — Maak een live trading account aan:\n\nRegistreer via deze link:\n👉 https://go.vtaffiliates.com/visit/?bta=42404&brand=vt\n\nAanbevolen platform: MetaTrader 5\nAccounttype: RAW-ECN\nValuta: EUR",
    },
    "verify_identity": {
        "en": "Step 2️⃣ — Verify your identity:\n\nComplete the identity verification inside VT Markets (one-time only) to fully activate your account.",
        "es": "Paso 2️⃣ — Verifica tu identidad:\n\nCompleta la verificación en VT Markets para activar tu cuenta.",
        "fr": "Étape 2️⃣ — Vérifiez votre identité :\n\nComplétez la vérification dans VT Markets.",
        "de": "Schritt 2️⃣ — Verifiziere deine Identität:\n\nSchließe die Verifizierung bei VT Markets ab.",
        "pt": "Passo 2️⃣ — Verifique sua identidade:\n\nComplete a verificação na VT Markets.",
        "ar": "الخطوة 2️⃣ — تحقق من هويتك:\n\nأكمل التحقق داخل VT Markets.",
        "hi": "स्टेप 2️⃣ — अपनी पहचान सत्यापित करें:\n\nVT Markets में सत्यापन पूरा करें।",
        "id": "Langkah 2️⃣ — Verifikasi identitas Anda:\n\nSelesaikan verifikasi di VT Markets.",
        "tr": "Adım 2️⃣ — Kimliğini doğrula:\n\nVT Markets içinde doğrulamayı tamamla.",
        "ru": "Шаг 2️⃣ — Подтвердите личность:\n\nЗавершите проверку в VT Markets.",
        "nl": "Stap 2️⃣ — Verifieer je identiteit:\n\nVoltooi verificatie binnen VT Markets.",
    },
    "fund_account": {
        "en": "Step 3️⃣ — Fund your account:\n\nTo trade XAUUSD using our execution model and required lot sizes, a minimum deposit of €350 is required.\n\n✅ After your deposit is confirmed, your balance will be doubled, providing you with additional capital to trade.",
        "es": "Paso 3️⃣ — Deposita en tu cuenta:\n\nPara operar XAUUSD, se requiere un depósito mínimo de €350.\n\n✅ Después de confirmar tu depósito, tu saldo se duplicará, dándote más capital para operar.",
        "fr": "Étape 3️⃣ — Approvisionnez votre compte :\n\nPour trader XAUUSD, un dépôt minimum de 350€ est requis.\n\n✅ Après confirmation du dépôt, votre solde sera doublé.",
        "de": "Schritt 3️⃣ — Konto aufladen:\n\nFür XAUUSD ist eine Mindesteinzahlung von 350€ erforderlich.\n\n✅ Nach Bestätigung wird dein Guthaben verdoppelt.",
        "pt": "Passo 3️⃣ — Financie sua conta:\n\nDepósito mínimo de €350 para negociar XAUUSD.\n\n✅ Após confirmação, seu saldo será dobrado.",
        "ar": "الخطوة 3️⃣ — قم بتمويل حسابك:\n\nالحد الأدنى للإيداع هو 350€ للتداول.\n\n✅ بعد التأكيد، سيتم مضاعفة رصيدك.",
        "hi": "स्टेप 3️⃣ — अपने अकाउंट में फंड करें:\n\nXAUUSD ट्रेड के लिए €350 न्यूनतम जमा आवश्यक है।\n\n✅ जमा के बाद बैलेंस डबल होगा।",
        "id": "Langkah 3️⃣ — Deposit dana:\n\nMinimal €350 untuk trading XAUUSD.\n\n✅ Setelah konfirmasi, saldo akan digandakan.",
        "tr": "Adım 3️⃣ — Hesabını fonla:\n\nXAUUSD için minimum €350 gerekir.\n\n✅ Onay sonrası bakiye iki katına çıkar.",
        "ru": "Шаг 3️⃣ — Пополните счет:\n\nМинимум €350 для торговли XAUUSD.\n\n✅ После подтверждения баланс удваивается.",
        "nl": "Stap 3️⃣ — Stort geld:\n\nMinimaal €350 vereist voor XAUUSD.\n\n✅ Na bevestiging wordt saldo verdubbeld.",
    },
    "upload_deposit_prompt": {
        "en": "Upload deposit proof.",
        "es": "Sube comprobante.",
        "fr": "Téléchargez preuve.",
        "de": "Nachweis hochladen.",
        "pt": "Envie comprovante.",
        "ar": "ارفع الإثبات.",
        "hi": "प्रूफ अपलोड करें।",
        "id": "Upload bukti.",
        "tr": "Kanıt yükle.",
        "ru": "Загрузите доказательство.",
        "nl": "Upload bewijs.",
    },
    "deposit_pending": {
        "en": "Deposit pending approval.",
        "es": "Pendiente.",
        "fr": "En attente.",
        "de": "Ausstehend.",
        "pt": "Pendente.",
        "ar": "قيد الانتظار.",
        "hi": "पेंडिंग।",
        "id": "Menunggu.",
        "tr": "Bekliyor.",
        "ru": "Ожидается.",
        "nl": "In afwachting.",
    },
    "deposit_approved": {
    "en": "Your deposit has been approved.\n\nRisk management is a critical aspect of trading. Before entering any trades, make sure you have reviewed the risk management module in your online training environment.\n\nDo you understand the importance of risk management?",
    "es": "Tu depósito ha sido aprobado.\n\nLa gestión de riesgos es un aspecto crítico del trading. Antes de realizar cualquier operación, asegúrate de haber revisado el módulo de gestión de riesgos en tu entorno de formación en línea.\n\n¿Entiendes la importancia de la gestión de riesgos?",
    "fr": "Votre dépôt a été approuvé.\n\nLa gestion des risques est un aspect essentiel du trading. Avant d'effectuer des transactions, assurez-vous d'avoir consulté le module de gestion des risques dans votre environnement de formation en ligne.\n\nComprenez-vous l'importance de la gestion des risques ?",
    "de": "Deine Einzahlung wurde bestätigt.\n\nRisikomanagement ist ein entscheidender Bestandteil des Tradings. Bevor du Trades eingehst, stelle sicher, dass du das Risikomanagement-Modul in deiner Online-Trainingsumgebung durchgesehen hast.\n\nVerstehst du die Bedeutung des Risikomanagements?",
    "pt": "Seu depósito foi aprovado.\n\nA gestão de risco é um aspecto crítico do trading. Antes de realizar qualquer operação, certifique-se de ter revisado o módulo de gestão de risco em seu ambiente de treinamento online.\n\nVocê entende a importância da gestão de risco?",
    "ar": "تمت الموافقة على الإيداع.\n\nإدارة المخاطر جزء أساسي من التداول. قبل الدخول في أي صفقات، تأكد من مراجعة وحدة إدارة المخاطر في بيئة التدريب الخاصة بك عبر الإنترنت.\n\nهل تفهم أهمية إدارة المخاطر؟",
    "hi": "आपका डिपॉज़िट स्वीकृत हो गया है।\n\nरिस्क मैनेजमेंट ट्रेडिंग का एक महत्वपूर्ण हिस्सा है। किसी भी ट्रेड में प्रवेश करने से पहले, सुनिश्चित करें कि आपने अपने ऑनलाइन प्रशिक्षण वातावरण में रिस्क मैनेजमेंट मॉड्यूल की समीक्षा कर ली है।\n\nक्या आप रिस्क मैनेजमेंट के महत्व को समझते हैं?",
    "id": "Deposit Anda telah disetujui.\n\nManajemen risiko adalah aspek penting dalam trading. Sebelum melakukan transaksi apa pun, pastikan Anda telah meninjau modul manajemen risiko di lingkungan pelatihan online Anda.\n\nApakah Anda memahami pentingnya manajemen risiko?",
    "tr": "Yatırımınız onaylandı.\n\nRisk yönetimi, tradingin kritik bir parçasıdır. Herhangi bir işlem yapmadan önce, çevrimiçi eğitim ortamınızdaki risk yönetimi modülünü gözden geçirdiğinizden emin olun.\n\nRisk yönetiminin önemini anlıyor musunuz?",
    "ru": "Ваш депозит был подтвержден.\n\nУправление рисками является важнейшей частью трейдинга. Перед тем как открывать сделки, убедитесь, что вы изучили модуль по управлению рисками в вашей онлайн-обучающей среде.\n\nПонимаете ли вы важность управления рисками?",
    "nl": "Je storting is goedgekeurd.\n\nRisicobeheer is een cruciaal onderdeel van handelen. Voordat je transacties uitvoert, zorg ervoor dat je de module risicobeheer in je online trainingsomgeving hebt doorgenomen.\n\nBegrijp je het belang van risicobeheer?"
    },
    "deposit_rejected": {
        "en": "Your deposit proof was rejected. Please upload it again.",
        "es": "Tu comprobante fue rechazado. Súbelo de nuevo.",
        "fr": "Votre preuve a été rejetée. Veuillez la télécharger à nouveau.",
        "de": "Nachweis abgelehnt. Bitte erneut hochladen.",
        "pt": "Comprovante rejeitado. Envie novamente.",
        "ar": "تم رفض الإثبات. أعد الرفع.",
        "hi": "आपका प्रूफ अस्वीकार किया गया। फिर से अपलोड करें।",
        "id": "Bukti ditolak. Upload ulang.",
        "tr": "Kanıt reddedildi. Tekrar yükle.",
        "ru": "Доказательство отклонено. Загрузите снова.",
        "nl": "Bewijs afgewezen. Upload opnieuw.",
    },

"risk": {
    "en": "Risk management is a critical aspect of trading.\n\nBefore entering any trades, make sure you have reviewed the risk management module in your online training environment.\n\nDo you understand the importance of risk management?",
    "es": "La gestión del riesgo es un aspecto crítico del trading.\n\nAntes de realizar cualquier operación, asegúrate de haber revisado el módulo de gestión de riesgos en tu entorno de formación en línea.\n\n¿Entiendes la importancia de la gestión del riesgo?",
    "fr": "La gestion des risques est un aspect essentiel du trading.\n\nAvant d’entrer dans une transaction, assurez-vous d’avoir consulté le module de gestion des risques dans votre environnement de formation en ligne.\n\nComprenez-vous l’importance de la gestion des risques ?",
    "de": "Risikomanagement ist ein entscheidender Bestandteil des Tradings.\n\nBevor du Trades eingehst, stelle sicher, dass du das Risikomanagement-Modul in deiner Online-Trainingsumgebung durchgesehen hast.\n\nVerstehst du die Bedeutung des Risikomanagements?",
    "pt": "A gestão de risco é um aspecto crítico do trading.\n\nAntes de realizar qualquer operação, certifique-se de ter revisado o módulo de gestão de risco em seu ambiente de treinamento online.\n\nVocê entende a importância da gestão de risco?",
    "ar": "إدارة المخاطر هي جانب أساسي في التداول.\n\nقبل الدخول في أي صفقة، تأكد من مراجعة وحدة إدارة المخاطر في بيئة التدريب الخاصة بك.\n\nهل تفهم أهمية إدارة المخاطر؟",
    "hi": "रिस्क मैनेजमेंट ट्रेडिंग का एक महत्वपूर्ण हिस्सा है।\n\nकिसी भी ट्रेड में प्रवेश करने से पहले, सुनिश्चित करें कि आपने अपने ऑनलाइन प्रशिक्षण वातावरण में रिस्क मैनेजमेंट मॉड्यूल की समीक्षा की है।\n\nक्या आप रिस्क मैनेजमेंट के महत्व को समझते हैं?",
    "id": "Manajemen risiko adalah aspek penting dalam trading.\n\nSebelum melakukan transaksi apa pun, pastikan Anda telah mempelajari modul manajemen risiko di lingkungan pelatihan online Anda.\n\nApakah Anda memahami pentingnya manajemen risiko?",
    "tr": "Risk yönetimi, tradingin kritik bir parçasıdır.\n\nHerhangi bir işlem yapmadan önce, çevrimiçi eğitim ortamınızdaki risk yönetimi modülünü incelediğinizden emin olun.\n\nRisk yönetiminin önemini anlıyor musunuz?",
    "ru": "Управление рисками является важнейшей частью трейдинга.\n\nПеред открытием сделок убедитесь, что вы изучили модуль по управлению рисками в вашей обучающей платформе.\n\nПонимаете ли вы важность управления рисками?",
    "nl": "Risicobeheer is een essentieel onderdeel van trading.\n\nVoordat je een trade plaatst, zorg ervoor dat je de risicobeheer module in je online trainingsomgeving hebt doorgenomen.\n\nBegrijp je het belang van risicobeheer?",
},

"risk_no": {
  "en": "Risk management is the foundation of successful trading. Make sure you understand this before placing your first trade.",
  "es": "La gestión de riesgos es la base del trading exitoso. Asegúrate de entender esto antes de realizar tu primera operación.",
  "fr": "La gestion des risques est la base d’un trading réussi. Assurez-vous de bien comprendre cela avant d’effectuer votre première transaction.",
  "de": "Risikomanagement ist die Grundlage für erfolgreiches Trading. Stelle sicher, dass du dies verstehst, bevor du deinen ersten Trade platzierst.",
  "pt": "A gestão de risco é a base de um trading bem-sucedido. Certifique-se de entender isso antes de realizar sua primeira operação.",
  "ar": "إدارة المخاطر هي أساس التداول الناجح. تأكد من فهم ذلك قبل إجراء أول صفقة لك.",
  "hi": "रिस्क मैनेजमेंट सफल ट्रेडिंग की नींव है। अपनी पहली ट्रेड करने से पहले इसे अच्छी तरह समझ लें।",
  "id": "Manajemen risiko adalah dasar dari trading yang sukses. Pastikan Anda memahaminya sebelum melakukan transaksi pertama Anda.",
  "tr": "Risk yönetimi başarılı tradingin temelidir. İlk işleminizi yapmadan önce bunu anladığınızdan emin olun.",
  "ru": "Управление рисками — основа успешной торговли. Убедитесь, что вы понимаете это перед тем, как совершить свою первую сделку.",
  "nl": "Risicobeheer is de basis van succesvol handelen. Zorg ervoor dat je dit begrijpt voordat je je eerste transactie uitvoert."
},

"ready_to_trade": {
    "en": "You are ready to place your first trades with us.\n\nIf you’re not sure how to connect your VT Markets account to MetaTrader 4 or 5 and start trading, watch the video below.",
    "es": "Ya estás listo para realizar tus primeras operaciones con nosotros.\n\nSi no sabes cómo conectar tu cuenta de VT Markets a MetaTrader 4 o 5 y comenzar a operar, mira el video a continuación.",
    "fr": "Vous êtes prêt à effectuer vos premières opérations avec nous.\n\nSi vous ne savez pas comment connecter votre compte VT Markets à MetaTrader 4 ou 5, regardez la vidéo ci-dessous.",
    "de": "Du bist bereit, deine ersten Trades mit uns zu platzieren.\n\nWenn du nicht weißt, wie du dein VT Markets Konto mit MetaTrader 4 oder 5 verbindest, sieh dir das Video unten an.",
    "pt": "Você está pronto para fazer seus primeiros trades conosco.\n\nSe não souber como conectar sua conta VT Markets ao MetaTrader 4 ou 5, assista ao vídeo abaixo.",
    "ar": "أنت الآن جاهز لبدء التداول معنا.\n\nإذا لم تكن تعرف كيفية ربط حساب VT Markets الخاص بك بـ MetaTrader 4 أو 5، شاهد الفيديو أدناه.",
    "hi": "आप अब हमारे साथ अपना पहला ट्रेड करने के लिए तैयार हैं।\n\nयदि आपको नहीं पता कि VT Markets अकाउंट को MetaTrader 4 या 5 से कैसे जोड़ें, तो नीचे दिया गया वीडियो देखें।",
    "id": "Anda siap untuk mulai trading bersama kami.\n\nJika Anda belum tahu cara menghubungkan akun VT Markets ke MetaTrader 4 atau 5, tonton video di bawah ini.",
    "tr": "Artık bizimle ilk işlemlerinizi yapmaya hazırsınız.\n\nVT Markets hesabınızı MetaTrader 4 veya 5’e nasıl bağlayacağınızı bilmiyorsanız aşağıdaki videoyu izleyin.",
    "ru": "Вы готовы начать свои первые сделки с нами.\n\nЕсли вы не знаете, как подключить счет VT Markets к MetaTrader 4 или 5, посмотрите видео ниже.",
    "nl": "Je bent klaar om je eerste trades met ons te plaatsen.\n\nAls je niet weet hoe je je VT Markets account koppelt aan MetaTrader 4 of 5, bekijk dan de video hieronder."
},
"premium_granted": {
    "en": "Access to our Exclusive Trading Alerts is granted.\n\nClick below to join now.",
    "es": "Se te ha concedido acceso a nuestras alertas exclusivas de trading.\n\nHaz clic abajo para unirte ahora.",
    "fr": "L’accès à nos alertes de trading exclusives vous a été accordé.\n\nCliquez ci-dessous pour rejoindre maintenant.",
    "de": "Der Zugriff auf unsere exklusiven Trading-Alerts wurde dir gewährt.\n\nKlicke unten, um jetzt beizutreten.",
    "pt": "O acesso aos nossos alertas exclusivos de trading foi concedido.\n\nClique abaixo para entrar agora.",
    "ar": "تم منحك الوصول إلى تنبيهات التداول الحصرية الخاصة بنا.\n\nاضغط أدناه للانضمام الآن.",
    "hi": "आपको हमारे एक्सक्लूसिव ट्रेडिंग अलर्ट्स का एक्सेस मिल गया है।\n\nअभी जुड़ने के लिए नीचे क्लिक करें।",
    "id": "Akses ke sinyal trading eksklusif kami telah diberikan.\n\nKlik di bawah untuk bergabung sekarang.",
    "tr": "Özel trading sinyallerimize erişim sağlandı.\n\nŞimdi katılmak için aşağıya tıklayın.",
    "ru": "Вам предоставлен доступ к нашим эксклюзивным торговым сигналам.\n\nНажмите ниже, чтобы присоединиться сейчас.",
    "nl": "Je hebt toegang gekregen tot onze exclusieve trading alerts.\n\nKlik hieronder om nu deel te nemen.",
},
    "unsupported_file": {
        "en": "Unsupported file. Please upload an image or PDF.",
        "es": "Archivo no compatible. Sube una imagen o PDF.",
        "fr": "Fichier non pris en charge. Téléchargez une image ou PDF.",
        "de": "Datei nicht unterstützt. Bitte Bild oder PDF hochladen.",
        "pt": "Arquivo não suportado. Envie imagem ou PDF.",
        "ar": "ملف غير مدعوم. ارفع صورة أو PDF.",
        "hi": "अमान्य फ़ाइल। इमेज या PDF अपलोड करें।",
        "id": "File tidak didukung. Upload gambar atau PDF.",
        "tr": "Desteklenmeyen dosya. Görsel veya PDF yükle.",
        "ru": "Файл не поддерживается. Загрузите изображение или PDF.",
        "nl": "Bestand niet ondersteund. Upload een afbeelding of PDF.",
    },

    "status_waiting_deposit": {
        "en": "Your deposit is still pending approval.",
        "es": "Tu depósito está pendiente.",
        "fr": "Votre dépôt est en attente.",
        "de": "Deine Einzahlung wartet.",
        "pt": "Seu depósito está pendente.",
        "ar": "الإيداع قيد الانتظار.",
        "hi": "आपका डिपॉज़िट लंबित है।",
        "id": "Deposit masih menunggu.",
        "tr": "Yatırım beklemede.",
        "ru": "Депозит ожидает.",
        "nl": "Je storting is in afwachting.",
    },
    "admin_deposit_caption": _same("New deposit proof submitted."),
    "admin_trade_caption": _same("New first trade proof submitted."),
    "trading_video_missing": _same("Trading video is not configured yet. The admin needs to upload it first."),
    "admin_only": _same("This action is only available to admins."),
    "saved": {
        "en": "Saved successfully.",
        "es": "Guardado.",
        "fr": "Enregistré.",
        "de": "Gespeichert.",
        "pt": "Salvo.",
        "ar": "تم الحفظ.",
        "hi": "सेव हो गया।",
        "id": "Disimpan.",
        "tr": "Kaydedildi.",
        "ru": "Сохранено.",
        "nl": "Opgeslagen.",
    },
}


def t(key: str, language: str) -> str:
    bundle = TEXTS.get(key, {})
    return bundle.get(language) or bundle.get("en") or key
